org: arcturus91
app: aws-node-project
service: aws-node-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  app-api:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

